apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: rest-api
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: DB_URL
              value: jdbc:postgresql://postgresql-service:5432/cinema
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              value: postgres
