version: "3.9"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "cinema"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/cinema
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
