version: "3.9"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "cinema"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
  
  spring-server:
    image: cinema-server:latest
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_DATABASE_URL=jdbc:postgresql://postgres:5432/cinema
